create table if not exists auth.login_logs (
  id bigint generated by default as identity primary key,
  email varchar(320),
  user_id bigint,
  success boolean not null,
  failure_code varchar(50),
  failure_message text,
  client_ip varchar(45),
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists idx_login_logs_created_at on auth.login_logs (created_at desc);
create index if not exists idx_login_logs_email on auth.login_logs (email);
create index if not exists idx_login_logs_user_id on auth.login_logs (user_id);
create index if not exists idx_login_logs_success on auth.login_logs (success);

comment on table auth.login_logs is '로그인 시도 이력';
comment on column auth.login_logs.id is '로그인 로그 식별자';
comment on column auth.login_logs.email is '로그인 시도 이메일';
comment on column auth.login_logs.user_id is '회원 식별자';
comment on column auth.login_logs.success is '로그인 성공 여부';
comment on column auth.login_logs.failure_code is '실패 코드';
comment on column auth.login_logs.failure_message is '실패 메시지';
comment on column auth.login_logs.client_ip is '요청 클라이언트 IP';
comment on column auth.login_logs.user_agent is '요청 사용자 에이전트';
comment on column auth.login_logs.created_at is '생성 시각';
