create table if not exists auth.refresh_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint not null references auth.users(id),
  token_hash varchar(255) not null,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  constraint uk_refresh_token_hash unique (token_hash)
);

create index if not exists idx_rt_user_id on auth.refresh_tokens (user_id);
create index if not exists idx_rt_active on auth.refresh_tokens (user_id) where revoked_at is null;

comment on table auth.refresh_tokens is '리프레시 토큰 저장소';
comment on column auth.refresh_tokens.id is '리프레시 토큰 식별자';
comment on column auth.refresh_tokens.user_id is '회원 식별자';
comment on column auth.refresh_tokens.token_hash is '리프레시 토큰 해시값';
comment on column auth.refresh_tokens.expires_at is '토큰 만료 시각';
comment on column auth.refresh_tokens.revoked_at is '토큰 폐기 시각';
comment on column auth.refresh_tokens.created_at is '생성 시각';
