create table if not exists auth.error_logs (
  id bigint generated by default as identity primary key,
  status int not null,
  code varchar(50) not null,
  message text not null,
  path text not null,
  method varchar(10) not null,
  user_id bigint,
  user_agent text,
  client_ip varchar(45),
  stack_trace text,
  created_at timestamptz not null default now()
);

create index if not exists idx_error_logs_created_at on auth.error_logs (created_at desc);
create index if not exists idx_error_logs_code on auth.error_logs (code);
create index if not exists idx_error_logs_status on auth.error_logs (status);
create index if not exists idx_error_logs_path on auth.error_logs (path);
create index if not exists idx_error_logs_user_id on auth.error_logs (user_id);

comment on table auth.error_logs is 'API 오류 로그';
comment on column auth.error_logs.id is '오류 로그 식별자';
comment on column auth.error_logs.status is 'HTTP 상태 코드';
comment on column auth.error_logs.code is '애플리케이션 오류 코드';
comment on column auth.error_logs.message is '오류 메시지';
comment on column auth.error_logs.path is '요청 경로';
comment on column auth.error_logs.method is 'HTTP 메서드';
comment on column auth.error_logs.user_id is '요청 회원 식별자';
comment on column auth.error_logs.user_agent is '요청 사용자 에이전트';
comment on column auth.error_logs.client_ip is '요청 클라이언트 IP';
comment on column auth.error_logs.stack_trace is '스택 트레이스';
comment on column auth.error_logs.created_at is '생성 시각';
