create table if not exists auth.users (
  id bigint generated by default as identity primary key,
  email varchar(320),
  password_hash varchar(255),
  tier varchar(20) not null references auth.tiers(tier_cd),
  status varchar(30) not null,
  phone varchar(30),
  display_name varchar(50),
  last_login_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uk_users_email unique (email),
  constraint uk_users_phone unique (phone),
  constraint chk_users_status
    check (status in ('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'DELETED'))
);

create index if not exists idx_users_tier on auth.users (tier);
create index if not exists idx_users_status on auth.users (status);

create trigger trg_users_updated_at
before update on auth.users
for each row
execute function auth.touch_updated_at();

comment on table auth.users is '회원 계정 기본 정보';
comment on column auth.users.id is '회원 식별자';
comment on column auth.users.email is '로그인 이메일';
comment on column auth.users.password_hash is '비밀번호 해시';
comment on column auth.users.tier is '회원 등급 코드';
comment on column auth.users.status is '회원 상태';
comment on column auth.users.phone is '휴대폰 번호';
comment on column auth.users.display_name is '표시 이름';
comment on column auth.users.last_login_at is '마지막 로그인 시각';
comment on column auth.users.deleted_at is '소프트 삭제 시각';
comment on column auth.users.created_at is '생성 시각';
comment on column auth.users.updated_at is '수정 시각';
