create table if not exists auth.email_verifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references auth.users(id),
  email varchar(320) not null,
  code_hash varchar(255) not null,
  expires_at timestamptz not null,
  verified_at timestamptz,
  attempt_count integer not null default 0,
  extend_window_start timestamptz,
  extend_window_count integer not null default 0,
  created_at timestamptz not null default now(),
  constraint chk_ev_attempt_count check (attempt_count >= 0)
);

create index if not exists idx_ev_user_id on auth.email_verifications (user_id);
create index if not exists idx_ev_email_created on auth.email_verifications (email, created_at desc);
create index if not exists idx_ev_unverified on auth.email_verifications (email) where verified_at is null;

comment on table auth.email_verifications is '이메일 인증 코드 발급 및 검증 이력';
comment on column auth.email_verifications.id is '이메일 인증 식별자';
comment on column auth.email_verifications.user_id is '회원 식별자';
comment on column auth.email_verifications.email is '인증 대상 이메일';
comment on column auth.email_verifications.code_hash is '인증 코드 해시값';
comment on column auth.email_verifications.expires_at is '인증 코드 만료 시각';
comment on column auth.email_verifications.verified_at is '인증 완료 시각';
comment on column auth.email_verifications.attempt_count is '인증 시도 횟수';
comment on column auth.email_verifications.extend_window_start is '인증 연장 윈도우 시작 시각';
comment on column auth.email_verifications.extend_window_count is '인증 연장 횟수';
comment on column auth.email_verifications.created_at is '생성 시각';
