create table if not exists auth.error_logs (
  id         bigint generated by default as identity primary key,
  status     int not null,
  code       varchar(50) not null,
  message    text not null,
  path       text not null,
  method     varchar(10) not null,
  user_id    bigint null,
  user_agent text null,
  client_ip  varchar(45) null,
  stack_trace text null,
  created_at timestamptz not null default now()
);

create index if not exists idx_error_logs_created_at on auth.error_logs (created_at desc);
create index if not exists idx_error_logs_code on auth.error_logs (code);
create index if not exists idx_error_logs_status on auth.error_logs (status);
create index if not exists idx_error_logs_path on auth.error_logs (path);
create index if not exists idx_error_logs_user_id on auth.error_logs (user_id);
