create table if not exists auth.login_logs (
  id             bigint generated by default as identity primary key,
  email          varchar(320) not null,
  user_id        bigint null,
  success        boolean not null,
  failure_code   varchar(50) null,
  failure_message text null,
  client_ip      varchar(45) null,
  user_agent     text null,
  created_at     timestamptz not null default now()
);

create index if not exists idx_login_logs_created_at on auth.login_logs (created_at desc);
create index if not exists idx_login_logs_email on auth.login_logs (email);
create index if not exists idx_login_logs_user_id on auth.login_logs (user_id);
create index if not exists idx_login_logs_success on auth.login_logs (success);
