-- PetYard Auth Tier0 schema (PostgreSQL 16+)
-- NOTE: Tier/Permission 정책 SSOT는 코드(UserTier#permissions())에 있으며,
--       DB의 auth.tiers는 표시/참조용 메타 데이터만 담당한다.

create schema if not exists auth;
CREATE SCHEMA IF NOT EXISTS pet;
create schema if not exists core; -- TODO: 공용 도메인 스키마(향후 사용)

-- 설계 메모:
-- 1) tier/status는 초기에는 TEXT + CHECK로 관리한다.
--    이유: 초기 마이그레이션 시 유연성과 배포 안전성 확보.
--    (추후 PG ENUM으로 전환 가능)
-- 2) Tier1/Tier2 확장 시 users 테이블은 유지하고,
--    pet_profile 등은 별도 테이블/스키마로 확장한다.
-- 3) deleted_at은 soft delete 확장 대비 컬럼이다.

-- 공용 updated_at 자동 갱신 함수
create or replace function auth.touch_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Tier 메타 테이블 (표시/참조 전용)
create table if not exists auth.tiers (
  tier_cd     varchar(20) primary key,
  tier_nm     varchar(50) not null,
  description text null,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists idx_tiers_is_active on auth.tiers (is_active);

create trigger trg_tiers_updated_at
before update on auth.tiers
for each row
execute function auth.touch_updated_at();

comment on table auth.tiers is 'Tier 메타 데이터(표시/참조용). 권한 정책 SSOT는 코드에 있음.';
comment on column auth.tiers.tier_cd is 'Tier 코드 (UserTier enum name과 동일 문자열)';
comment on column auth.tiers.tier_nm is '표시명';
comment on column auth.tiers.description is '설명';
comment on column auth.tiers.is_active is '활성 여부';
comment on column auth.tiers.created_at is '생성 시각(UTC)';
comment on column auth.tiers.updated_at is '수정 시각(UTC)';

-- seed (upsert)
insert into auth.tiers (tier_cd, tier_nm, description)
values
  ('TIER_0', '기본 인증 사용자', '이메일 인증 완료 사용자'),
  ('TIER_1', '반려동물 인증 사용자', '반려동물 인증 완료 사용자'),
  ('TIER_2', '신뢰 사용자', '신뢰 기준 충족 사용자')
on conflict (tier_cd)
do update set
  tier_nm = excluded.tier_nm,
  description = excluded.description,
  is_active = true,
  updated_at = now();

-- users 테이블
create table if not exists auth.users (
  id             bigint generated by default as identity primary key,
  email          varchar(320) not null,
  password_hash  varchar(255) not null,
  tier           varchar(20) not null references auth.tiers(tier_cd),
  status         varchar(30) not null,
  phone          varchar(30) null,
  display_name   varchar(50) null,
  last_login_at  timestamptz null,
  deleted_at     timestamptz null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  constraint uk_users_email unique (email),
  constraint uk_users_phone unique (phone),
  constraint chk_users_status
    check (status in ('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'DELETED'))
);

create index if not exists idx_users_tier on auth.users (tier);
create index if not exists idx_users_status on auth.users (status);

create trigger trg_users_updated_at
before update on auth.users
for each row
execute function auth.touch_updated_at();

comment on table auth.users is '회원 계정 (Tier0 인증/로그인 기준)';
comment on column auth.users.id is '회원 PK';
comment on column auth.users.email is '이메일(로그인 ID)';
comment on column auth.users.password_hash is 'BCrypt 비밀번호 해시';
comment on column auth.users.tier is 'Tier 코드(FK). 권한 SSOT는 코드에 있음';
comment on column auth.users.status is '계정 상태';
comment on column auth.users.phone is '휴대폰 번호(선택)';
comment on column auth.users.display_name is '표시명(선택)';
comment on column auth.users.last_login_at is '마지막 로그인 시각(UTC)';
comment on column auth.users.deleted_at is '소프트 삭제 시각(UTC)';
comment on column auth.users.created_at is '생성 시각(UTC)';
comment on column auth.users.updated_at is '수정 시각(UTC)';

-- email_verifications 테이블
create table if not exists auth.email_verifications (
  id            bigint generated by default as identity primary key,
  user_id       bigint not null references auth.users(id),
  email         varchar(320) not null,
  code_hash     varchar(255) not null,
  expires_at    timestamptz not null,
  verified_at   timestamptz null,
  attempt_count int not null default 0,
  created_at    timestamptz not null default now(),
  constraint chk_ev_attempt_count check (attempt_count >= 0)
);

create index if not exists idx_ev_user_id on auth.email_verifications (user_id);
create index if not exists idx_ev_email_created on auth.email_verifications (email, created_at desc);
create index if not exists idx_ev_unverified on auth.email_verifications (email) where verified_at is null;

comment on table auth.email_verifications is '이메일 OTP 인증 기록 (평문 저장 금지)';
comment on column auth.email_verifications.user_id is '회원 FK';
comment on column auth.email_verifications.email is '이메일 조회 편의용';
comment on column auth.email_verifications.code_hash is 'OTP 해시';
comment on column auth.email_verifications.expires_at is '만료 시각(UTC)';
comment on column auth.email_verifications.verified_at is '인증 완료 시각(UTC)';
comment on column auth.email_verifications.attempt_count is '인증 시도 횟수';
comment on column auth.email_verifications.created_at is '생성 시각(UTC)';

-- refresh_tokens 테이블
create table if not exists auth.refresh_tokens (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references auth.users(id),
  token_hash varchar(255) not null,
  expires_at timestamptz not null,
  revoked_at timestamptz null,
  created_at timestamptz not null default now(),
  constraint uk_refresh_token_hash unique (token_hash)
);

create index if not exists idx_rt_user_id on auth.refresh_tokens (user_id);
create index if not exists idx_rt_active on auth.refresh_tokens (user_id) where revoked_at is null;

comment on table auth.refresh_tokens is '리프레시 토큰 저장(평문 금지, 회전 지원)';
comment on column auth.refresh_tokens.user_id is '회원 FK';
comment on column auth.refresh_tokens.token_hash is '리프레시 토큰 해시';
comment on column auth.refresh_tokens.expires_at is '만료 시각(UTC)';
comment on column auth.refresh_tokens.revoked_at is '폐기 시각(UTC)';
comment on column auth.refresh_tokens.created_at is '생성 시각(UTC)';
