CREATE TABLE IF NOT EXISTS pet.breeds (
  id bigserial PRIMARY KEY,
  species varchar(16) NOT NULL,
  name_ko varchar(120) NOT NULL,
  name_en varchar(120),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pet_breeds_species ON pet.breeds(species);

INSERT INTO pet.breeds (species, name_ko, name_en) VALUES
  ('DOG', '포메라니안', 'Pomeranian'),
  ('DOG', '말티즈', 'Maltese'),
  ('DOG', '푸들', 'Poodle'),
  ('DOG', '비숑 프리제', 'Bichon Frise'),
  ('DOG', '시바 이누', 'Shiba Inu'),
  ('DOG', '치와와', 'Chihuahua'),
  ('DOG', '닥스훈트', 'Dachshund'),
  ('DOG', '웰시 코기', 'Welsh Corgi'),
  ('DOG', '골든 리트리버', 'Golden Retriever'),
  ('DOG', '래브라도 리트리버', 'Labrador Retriever'),
  ('DOG', '보더 콜리', 'Border Collie'),
  ('DOG', '시츄', 'Shih Tzu'),
  ('DOG', '요크셔 테리어', 'Yorkshire Terrier'),
  ('DOG', '퍼그', 'Pug'),
  ('DOG', '비글', 'Beagle'),
  ('DOG', '사모예드', 'Samoyed'),
  ('DOG', '허스키', 'Siberian Husky'),
  ('DOG', '믹스견', 'Mixed'),
  ('DOG', '진돗개', 'Jindo'),
  ('DOG', '스피츠', 'Spitz'),
  ('CAT', '코리안 숏헤어', 'Korean Shorthair'),
  ('CAT', '러시안 블루', 'Russian Blue'),
  ('CAT', '스코티시 폴드', 'Scottish Fold'),
  ('CAT', '아메리칸 숏헤어', 'American Shorthair'),
  ('CAT', '브리티시 숏헤어', 'British Shorthair'),
  ('CAT', '노르웨이 숲', 'Norwegian Forest'),
  ('CAT', '메인쿤', 'Maine Coon'),
  ('CAT', '페르시안', 'Persian'),
  ('CAT', '샴', 'Siamese'),
  ('CAT', '터키시 앙고라', 'Turkish Angora'),
  ('CAT', '먼치킨', 'Munchkin'),
  ('CAT', '랙돌', 'Ragdoll'),
  ('CAT', '벵갈', 'Bengal'),
  ('CAT', '아비시니안', 'Abyssinian'),
  ('CAT', '아메리칸 컬', 'American Curl'),
  ('CAT', '브리티시 롱헤어', 'British Longhair'),
  ('CAT', '스핑크스', 'Sphynx'),
  ('CAT', '히말라얀', 'Himalayan'),
  ('CAT', '믹스묘', 'Mixed'),
  ('CAT', '엑조틱 숏헤어', 'Exotic Shorthair');
